### ISSUE TITLE
DXEchoEffect.ApplyOn throws System.ArgumentException

### ISSUE THREAD

**Issue by ClonkAndre** [ManagedBass/ManagedBass#120]
Hello, i'm trying to add the DXEchoEffect on a Stream.
But if i try to call the ApplyOn method, i'm getting the exception below.

**The exception i'm getting**
Details: System.ArgumentException: The object does not contain any primitive data.
   at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle..ctor(Object value, GCHandleType type)
   at ManagedBass.Effect`1.ApplyOn(Int32 Channel, Int32 Priority)
   at ExtraSoundsIV.Main.PlacedSound.AddEchoEffect()

**The code**
`if (Handle == 0)
    return;

if (EchoEffect == null)
{
    EchoEffect = new DXEchoEffect();
    EchoEffect.ApplyOn(Handle);
    EchoEffect.IsActive = true;
}`

Any help would be appreciated!

**Comment by ClonkAndre** [comment]
I don't believe so, no. It's been a while. I would appreciate if you could look into this tho, it's a great library for quickly throwing together a good working audio system.
