### ISSUE TITLE
Suspected leak while using the FileProcedures callback/wrapper class

### ISSUE THREAD

**Issue by StefanRademakers** [ManagedBass/ManagedBass#68]
**Issue with FileProcedures class**
Issue: Application eventually stalls and then crashes on Android (resulting in an Application not responding error eventually). This usually happens when samples are played at a rappid speed behind each other.

**Test situation**
In our test code we run over 850 samples in a Task.Run. We play the samples from an expansion pack, we use the StreamFileProcedures class en input it with:
```
foreach (var audiofile in samples) {
      var fileAfd = files.GetAssetFileDescriptor(audiofile);
      var streamAssetWrapper = new StreamFileProcedures(fileAfd.CreateInputStream(), fileAfd.Length);
      var _stream = Bass.CreateStream(StreamSystem.Buffer, BassFlags.AutoFree, streamAssetWrapper);
      Bass.ChannelPlay(_stream);
      await Task.Delay(500);
      StopStream(_stream);
      await Task.Delay(500);
}

```
**We use the tag AutoFree, the fileprocedures class states the following:**
A copy is made of the FileProcedures callback function table, so it does not have to persist beyond this function call. Unlike Bass.Net, a reference to FileProcedures doesn't need to be held by you manually. ManagedBass automatically holds a reference and frees it when the Channel is freed
  
**Suspected actual behaviour:**
ManagedBass does not release the reference somewhere to the input stream, resulting in a leak?

**Android log**
12-03 14:04:15.324  6944 19145 E rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
12-03 14:04:15.325  6944 25052 E rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
12-03 14:04:15.325  6944 25052 E rs$DefaultThreadFactory: dalvik.system.VMStack.getThreadStackTrace(Native Method)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: java.lang.Thread.getStackTrace(Thread.java:1538)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:569)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: tdo.newThread(Unknown Source:9)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:636)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1393)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: sxs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):5)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: sxs.execute(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: dalvik.system.VMStack.getThreadStackTrace(Native Method)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: brcf.execute(:com.google.android.gms@19629030@19.6.29 (100408-278422107):1)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: java.lang.Thread.getStackTrace(Thread.java:1538)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:569)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):39)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: tdo.newThread(Unknown Source:9)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: bqzw.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:636)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: betz.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):5)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: blnl.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1393)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: bqzu.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: sxs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):5)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: sxs.execute(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: brcq.execute(:com.google.android.gms@19629030@19.6.29 (100408-278422107):8)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: brao.d(:com.google.android.gms@19629030@19.6.29 (100408-278422107):1)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: brap.g(Unknown Source:4)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: braa.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):12)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: bqzx.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: braq.execute(Unknown Source:0)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):39)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: braa.d(:com.google.android.gms@19629030@19.6.29 (100408-278422107):3)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: brap.<init>(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: brbj.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):3)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: bewk.c(Unknown Source:22)
12-03 14:04:15.326  6944 19145 E rs$DefaultThreadFactory: bewk.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):11)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: beuv.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):13)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: beuv.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):8)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bcnh.a(Unknown Source:4)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bcmr.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: beik.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bqzu.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bqzw.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):11)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: braq.execute(Unknown Source:0)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):39)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bqzw.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: brbb.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):5)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: beii.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):3)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bqzu.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.326  6944 25052 E rs$DefaultThreadFactory: bqzw.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):11)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: braq.execute(Unknown Source:0)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):39)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: bqzw.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: betx.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):7)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: blnj.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: brav.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: brcx.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: brbw.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):7)
12-03 14:04:15.327  6944 25052 E rs$DefaultThreadFactory: brcz.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):1)
12-03 14:04:15.328  6944 25052 E rs$DefaultThreadFactory: sxr.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):15)
12-03 14:04:15.328  6944 25052 E rs$DefaultThreadFactory: sxr.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):10)
12-03 14:04:15.328  6944 25052 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-03 14:04:15.328  6944 25052 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-03 14:04:15.328  6944 25052 E rs$DefaultThreadFactory: tdp.run(Unknown Source:7)
12-03 14:04:15.328  6944 25052 E rs$DefaultThreadFactory: java.lang.Thread.run(Thread.java:764)
12-03 14:04:15.327  6944 19145 E rs$DefaultThreadFactory: bqzw.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):11)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: braq.execute(Unknown Source:0)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):30)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):15)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqze.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: braq.execute(Unknown Source:0)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):30)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):15)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzv.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):3)
12-03 14:04:15.328  6944 19145 E rs$DefaultThreadFactory: bqzw.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: braq.execute(Unknown Source:0)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):30)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):8)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: brbk.run(Unknown Source:4)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: braq.execute(Unknown Source:0)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):4)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: bqzs.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):30)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: bqzs.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):8)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: brcx.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):3)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: brbw.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):2)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: brcz.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):1)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: sxr.b(:com.google.android.gms@19629030@19.6.29 (100408-278422107):15)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: sxr.run(:com.google.android.gms@19629030@19.6.29 (100408-278422107):10)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: tdp.run(Unknown Source:7)
12-03 14:04:15.329  6944 19145 E rs$DefaultThreadFactory: java.lang.Thread.run(Thread.java:764)

**StrictMode policy violation log**
12-03 14:02:48.558 20640 20650 D StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
12-03 14:02:48.558 20640 20650 D StrictMode: 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1786)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.finalize(ParcelFileDescriptor.java:988)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at java.lang.Thread.run(Thread.java:764)
12-03 14:02:48.558 20640 20650 D StrictMode: Caused by: java.lang.Throwable: Explicit termination method 'close' not called
12-03 14:02:48.558 20640 20650 D StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:221)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:192)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:181)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:214)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at com.google.android.vending.expansion.zipfile.ZipResourceFile$ZipEntryRO.getAssetFileDescriptor(ZipResourceFile.java:163)
12-03 14:02:48.558 20640 20650 D StrictMode: 	at com.google.android.vending.expansion.zipfile.ZipResourceFile.getAssetFileDescriptor(ZipResourceFile.java:228)
12-03 14:02:48.574 20640 20650 I chatty  : uid=10395(nl.mediavibe.rpgsoundscapes) identical 6 lines
12-03 14:02:48.577 20640 20650 D StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
12-03 14:02:48.577 20640 20650 D StrictMode: 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1786)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.finalize(ParcelFileDescriptor.java:988)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at java.lang.Thread.run(Thread.java:764)
12-03 14:02:48.577 20640 20650 D StrictMode: Caused by: java.lang.Throwable: Explicit termination method 'close' not called
12-03 14:02:48.577 20640 20650 D StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:221)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:192)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:181)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:214)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at com.google.android.vending.expansion.zipfile.ZipResourceFile$ZipEntryRO.getAssetFileDescriptor(ZipResourceFile.java:163)
12-03 14:02:48.577 20640 20650 D StrictMode: 	at com.google.android.vending.expansion.zipfile.ZipResourceFile.getAssetFileDescriptor(ZipResourceFile.java:228)

**Comment by vandenbrakel** [comment]
Any information on this?
